name: pygenefinder
version: 'latest'
#version-script: git describe --abbrev=1 --tags
summary: microbial gene finder
description: |
  pygenefinder is an open source desktop application
  for microbial gene identification in sequence data

base: core18
grade: stable
confinement: strict
icon: gui/icon.png

apps:
  pygenefinder:
    command: desktop-launch $SNAP/bin/pygenefindergui
    plugs: [desktop,home]
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/ncbi-blast+
parts:
  pygenefinder:
    plugin: python
    python-version: python3
    source: ../
    stage-packages:
      - ncbi-blast+
      - clustalw
      - prodigal
    python-packages:
      - PySide2
    after: [desktop-qt5]

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
        - libcairo-gobject2
